apiVersion: apps/v1
kind: Deployment
metadata:
  name: omnisolve-deployment
  labels:
    app: omnisolve-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: omnisolve-chatbot
  template:
    metadata:
      labels:
        app: omnisolve-chatbot
    spec:
      containers:
      - name: chatbot
        image: lokeshreddy45/chatbot:latest
        imagePullPolicy: IfNotPresent # Crucial for using local Docker images built on Minikube
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "200m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 3
          periodSeconds: 5
